export const MORE_INFO = 'MORE_INFO'
export const MORE_INFO_SUCCESS = 'MORE_INFO_SUCCESS'
export const CHANGE_SUPPORTS = 'CHANGE_SUPPORTS'
export const DELETE_SUPPORTS = 'DELETE_SUPPORTS'
export const EDIT_SUP_SUPPORTS = 'EDIT_SUPPORTS'
export const ALL_SUPPORTS = 'ALL_SUPPORTS'

